FROM test-base
RUN bash -c "$(curl -LSf "https://bitbucket.org/stroparo/runr/raw/master/entry.sh" \
    || curl -LSf "https://raw.githubusercontent.com/stroparo/runr/master/entry.sh")" \
    entry.sh alias dotfiles shell
 